#!/usr/bin/env python3
"""
Generate skills review infrastructure for auditing and validating skills.

This script:
1. Scans workspace for SKILL.md files in .github/skills/ directories
2. Generates docs/skills-review/skills.yaml with inventory of all skills
3. Creates individual review files at docs/skills-review/<skill-name>.md

Usage:
    python scripts/generate_skills_review.py                    # Generate skills.yaml
    python scripts/generate_skills_review.py --create-reviews   # Generate review files
    python scripts/generate_skills_review.py --apps frappe,erpnext  # Scan specific apps
"""

import argparse
import os
import re
from datetime import datetime
from pathlib import Path

import yaml

# Determine current app directory (where the script is located)
SCRIPT_DIR = Path(__file__).resolve().parent
APP_ROOT = SCRIPT_DIR.parent.parent.parent.parent  # Navigate up to app root


def parse_skill_frontmatter(skill_path):
    """
    Extract YAML frontmatter from a SKILL.md file.

    Returns dict with name, description, etc. or None if invalid.
    """
    try:
        with open(skill_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Match YAML frontmatter between --- delimiters
        match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
        if not match:
            return None

        frontmatter = yaml.safe_load(match.group(1))
        return frontmatter

    except Exception as e:
        print(f"Error parsing {skill_path}: {e}")
        return None


def scan_skills():
    """
    Scan current app for skills.

    Returns list of skill metadata dicts.
    """
    skills = []
    app_name = APP_ROOT.name
    skills_dir = APP_ROOT / ".github" / "skills"

    if not skills_dir.exists():
        print(f"Warning: Skills directory not found at {skills_dir}")
        return skills

    # Find all SKILL.md files
    for skill_md in skills_dir.glob("*/SKILL.md"):
        frontmatter = parse_skill_frontmatter(skill_md)

        if frontmatter and "name" in frontmatter:
            # Calculate relative path from app root
            rel_path = skill_md.relative_to(APP_ROOT)

            skill_info = {
                "name": frontmatter["name"],
                "description": frontmatter.get("description", ""),
                "path": str(rel_path),
                "enabled": False,  # Default to disabled
                "absolute_path": str(skill_md),
            }

            skills.append(skill_info)

    # Sort by name
    skills.sort(key=lambda s: s["name"])

    return skills


def generate_skills_yaml(skills, output_path):
    """
    Generate skills.yaml inventory file.
    """
    # Prepare data structure
    data = {
        "generated": datetime.now().isoformat(),
        "total_skills": len(skills),
        "skills": [
            {
                "name": s["name"],
                "path": s["path"],
                "enabled": s["enabled"],
                "description": (
                    s["description"][:100] + "..."
                    if len(s["description"]) > 100
                    else s["description"]
                ),
            }
            for s in skills
        ],
    }

    # Create output directory if needed
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Create .gitignore to exclude review markdown files from git
    gitignore_path = output_path.parent / ".gitignore"
    if not gitignore_path.exists():
        with open(gitignore_path, "w", encoding="utf-8") as f:
            f.write(
                "# Skill review markdown files are session-only and should not be committed\n"
            )
            f.write("*.md\n")
        print(f"✓ Created {gitignore_path}")

    # Write YAML
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Skills Review Inventory\n")
        f.write(
            "# Generated by .github/skills/skill-reviewer/scripts/generate_skills_review.py\n"
        )
        f.write("#\n")
        f.write("# Set enabled: true for skills you want to review\n")
        f.write(
            "# Then run: python .github/skills/skill-reviewer/scripts/generate_skills_review.py --create-reviews\n"
        )
        f.write("\n")
        yaml.dump(
            data, f, default_flow_style=False, allow_unicode=True, sort_keys=False
        )

    print(f"✓ Generated {output_path}")
    print(f"  Found {len(skills)} skills")


def get_skill_files(skill_path):
    """
    List all files in the skill directory.

    Returns list of relative paths from skill directory.
    """
    try:
        skill_file = Path(skill_path)
        skill_dir = skill_file.parent

        files = []

        # Always include SKILL.md
        files.append("SKILL.md")

        # Scan for additional files in skill directory
        for subdir in ["references", "scripts", "assets"]:
            subdir_path = skill_dir / subdir
            if subdir_path.exists() and subdir_path.is_dir():
                # Find all files recursively
                for file_path in subdir_path.rglob("*"):
                    if file_path.is_file():
                        rel_path = file_path.relative_to(skill_dir)
                        files.append(str(rel_path))

        return sorted(files)

    except Exception as e:
        print(f"Error listing skill files from {skill_path}: {e}")
        return ["SKILL.md"]


def generate_review_file(skill, output_path, force=False):
    """
    Generate individual review file for a skill.
    """
    if output_path.exists() and not force:
        print(f"  Skipping {skill['name']} (already exists, use --force to overwrite)")
        return

    # Get list of files in the skill directory
    skill_files = get_skill_files(skill["absolute_path"])

    # Generate review markdown
    content = f"""# Skill Review: {skill['name']}

**Skill Path**: `{skill['path']}`

{skill['description']}

## Review Checklist

### Code Accuracy
- [ ] All code examples are syntactically correct
- [ ] APIs and functions referenced still exist
- [ ] File paths and module imports are accurate
- [ ] DocType names and field references are current
- [ ] Database queries and ORM usage are valid

### Documentation Quality
- [ ] Description accurately reflects skill purpose
- [ ] Examples demonstrate real-world usage
- [ ] No deprecated features or patterns
- [ ] Links to referenced files are valid
- [ ] Prerequisites and dependencies are listed

### Consistency
- [ ] Follows current skill-creator guidelines
- [ ] Consistent with related skills
- [ ] No conflicting information
- [ ] Terminology matches framework conventions
- [ ] Formatting follows markdown best practices

### Completeness
- [ ] Covers the stated domain adequately
- [ ] Includes error handling patterns
- [ ] Shows both simple and complex cases
- [ ] References related skills where appropriate
- [ ] Includes troubleshooting guidance

### Relevance
- [ ] Addresses current user needs
- [ ] Examples use recent framework versions
- [ ] No outdated workarounds
- [ ] Aligns with framework direction

## Skill Files

Review all files in the skill directory:

"""

    if skill_files:
        for file in skill_files:
            content += f"- [ ] `{file}`\n"
    else:
        content += "_No additional files found in skill directory_\n"

    content += """
## Code Examples Review

<!-- For each code block in the skill, verify it works -->

- [ ] All Python code blocks are valid
- [ ] All JavaScript code blocks are valid
- [ ] All shell commands are current
- [ ] All API calls use correct signatures

## Notes

<!-- Add review notes here -->


## Action Items

<!-- List specific fixes needed -->

- [ ]

"""

    # Create output directory if needed
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write file
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"  ✓ Created review file for {skill['name']}")


def create_review_files(skills_yaml_path, output_dir, force=False):
    """
    Create review files for all enabled skills.
    """
    # Create output directory if needed
    output_dir.mkdir(parents=True, exist_ok=True)

    # Create .gitignore to exclude review markdown files from git
    gitignore_path = output_dir / ".gitignore"
    if not gitignore_path.exists():
        with open(gitignore_path, "w", encoding="utf-8") as f:
            f.write(
                "# Skill review markdown files are session-only and should not be committed\n"
            )
            f.write("*.md\n")
        print(f"✓ Created {gitignore_path}")

    # Load skills.yaml
    try:
        with open(skills_yaml_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except FileNotFoundError:
        print(
            f"Error: {skills_yaml_path} not found. Run without --create-reviews first."
        )
        return

    skills = data.get("skills", [])
    enabled_skills = [s for s in skills if s.get("enabled", False)]

    if not enabled_skills:
        print("No skills enabled for review.")
        print(f"Edit {skills_yaml_path} and set enabled: true for skills to review.")
        return

    print(f"Creating review files for {len(enabled_skills)} enabled skills...")

    for skill in enabled_skills:
        # Construct absolute path to skill
        skill_abs_path = APP_ROOT / skill["path"]

        if not skill_abs_path.exists():
            print(f"  Warning: {skill_abs_path} does not exist, skipping")
            continue

        # Add absolute path for reference extraction
        skill["absolute_path"] = str(skill_abs_path)

        # Generate review file
        review_file = output_dir / f"{skill['name']}.md"
        generate_review_file(skill, review_file, force=force)

    print(f"\n✓ Review files created in {output_dir}")
    print("\nNext steps:")
    print("1. Review each .md file in docs/skills-review/")
    print("2. Check off items as you validate them")
    print("3. Update skills as needed")
    print("4. Commit changes")


def main():
    parser = argparse.ArgumentParser(
        description="Generate skills review infrastructure for current app"
    )
    parser.add_argument(
        "--create-reviews",
        action="store_true",
        help="Create individual review files for enabled skills",
    )
    parser.add_argument(
        "--force", action="store_true", help="Overwrite existing review files"
    )
    parser.add_argument(
        "--output-dir",
        help="Output directory for review files (default: docs/skills-review)",
        default="docs/skills-review",
    )

    args = parser.parse_args()

    # Determine paths (relative to current app)
    output_dir = APP_ROOT / args.output_dir
    skills_yaml = output_dir / "skills.yaml"

    if args.create_reviews:
        # Create review files from existing skills.yaml
        create_review_files(skills_yaml, output_dir, force=args.force)
    else:
        # Scan and generate skills.yaml
        print(f"Scanning skills in {APP_ROOT.name} app...")
        skills = scan_skills()
        generate_skills_yaml(skills, skills_yaml)
        print(f"\nNext steps:")
        print(f"1. Edit {skills_yaml}")
        print(f"2. Set enabled: true for skills you want to review")
        print(
            f"3. Run: python .github/skills/skill-reviewer/scripts/generate_skills_review.py --create-reviews"
        )


if __name__ == "__main__":
    main()
